### ISSUE TITLE
update guzzle dependency

### ISSUE THREAD

**Issue by kamilsk** [paslandau/guzzle-rotating-proxy-subscriber#1]
Hi!
There is a need in this [version](https://github.com/paslandau/guzzle-rotating-proxy-subscriber/blob/master/composer.json#L21) of the client?
I mean >=5.0.3 <5.1 (https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-)

**Comment by kamilsk** [comment]
How about `"guzzlehttp/guzzle": "~5.0,>=5.0.3"`?

**Comment by paslandau** [comment]
Hey @kamilsk 

nope, mistake on my side. Just pushed a fix with some minor changes.

Thx for the info,

Cheers
Pascal
